language: go

go:
  - 1.12

services:
  - docker

before_install:
  - docker build -t autoapp .
  - go get github.com/mattn/goveralls

script:
  - go vet
  - $HOME/gopath/bin/goveralls -service=travis-ci
