---
version: 2
jobs:
  build:
    working_directory: /
    docker:
      - image: docker:stable-git
    steps:
      - run:
          name: Run tests
          command: |
            docker build -t testBuild .
