---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: autoapp-production
spec:
  replicas: 2
  template:
    metadata:
      name: frontend
      labels:
        app: autoapp-production
        role: frontend
        env: production
    spec:
      containers:
        - name: frontend
          image: quay.io/$QUAY_USER/autoapp
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          env:
            - name: NAME
              value: "To Production"
          ports:
            - name: frontend
              containerPort: 8080
