---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: autoapp-production
  name: autoapp-production
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: autoapp-production
    role: frontend
    env: production
  sessionAffinity: None
  type: LoadBalancer
